# Generated by Django 5.1.4 on 2025-08-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_restaurantprofile_integration_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='email',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
