# Generated by Django 5.1.4 on 2025-08-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_managerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
