# Generated by Django 5.1.4 on 2025-08-27 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customerprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='core.restaurantprofile'),
        ),
    ]
