# Generated by Django 5.1.4 on 2025-08-29 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ownership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownership',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='role',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='payout_status',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='processor_account_id',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='processor_verification',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='owners',
            field=models.ManyToManyField(related_name='restaurants', through='core.Ownership', to='core.ownerprofile'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='core.restaurantprofile'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
