# Generated by Django 5.1.4 on 2025-09-04 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_member_ticketlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.customerprofile'),
            preserve_default=False,
        ),
    ]
