# Generated by Django 5.1.4 on 2025-09-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_member_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
