# Generated by Django 5.1.4 on 2025-09-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='default_payment_method',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
