# Generated by Django 5.1.4 on 2025-09-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_customerprofile_default_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
