# Generated by Django 5.1.4 on 2025-09-13 00:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customerprofile_pin_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketlink',
            old_name='external_txn_id',
            new_name='auth_code',
        ),
        migrations.RenameField(
            model_name='ticketlink',
            old_name='last_total',
            new_name='change_cents',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ticketlink',
            name='location_id',
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='addr_line1',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='addr_line2',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='omnivore_location_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='postal',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='state',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='discounts_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='email_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='emailed_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='items_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='last_total_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='merchant_addr1',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='merchant_addr2',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='merchant_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='merchant_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='merchant_state',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='merchant_zip',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='paid_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='pos_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='pos_payment_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='pos_ref',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='pos_settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='raw_payments_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='raw_ticket_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_links', to='core.restaurantprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='subtotal_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='table',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='tax_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='tender_brand',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='tender_last4',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='tender_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='tip_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='total_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketlink',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketlink',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_links', to='core.member'),
        ),
        migrations.AlterField(
            model_name='ticketlink',
            name='opened_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticketlink',
            name='server_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='ticketlink',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed')], db_index=True, default='pending', max_length=12),
        ),
        migrations.AddIndex(
            model_name='ticketlink',
            index=models.Index(fields=['status', 'opened_at'], name='core_ticket_status_5b0498_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketlink',
            index=models.Index(fields=['status', 'closed_at'], name='core_ticket_status_fb9f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketlink',
            index=models.Index(fields=['ticket_id', 'status'], name='core_ticket_ticket__240ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketlink',
            index=models.Index(fields=['member', 'status'], name='core_ticket_member__239787_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketlink',
            constraint=models.UniqueConstraint(fields=('member', 'restaurant', 'ticket_id', 'status'), name='uniq_member_restaurant_ticket_by_status'),
        ),
    ]
