# Generated by Django 5.1.4 on 2025-09-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ownerinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='stripe_default_pm_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
