# Generated by Django 5.1.4 on 2025-09-15 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_restaurantprofile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantprofile',
            old_name='stripe_customer_id',
            new_name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='stripe_default_pm_id',
        ),
    ]
