# Generated by Django 5.1.4 on 2025-09-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_stripe_customer_id_restaurantprofile_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='stripe_cached',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
