# Generated by Django 5.1.4 on 2025-10-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='menu_cache',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='menu_cache_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='staff_cache',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='staff_cache_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
